## Setup

In [1]:
import importlib
from pathlib import Path
import sys
import polars as pl

pl.Config.set_tbl_rows(25)

REPO_DIR = Path('.').resolve().parent
DEV_DATA_DIR = REPO_DIR / 'trio_dev_data'

sys.path.insert(0, str(REPO_DIR / 'src'))
sys.path.insert(0, str(REPO_DIR / 'src' / 'util'))

from version_sort import version_sort

In [2]:
KID_ID = 'NA12878'
DAD_ID = 'NA12891'
MOM_ID = 'NA12892'

METH_BASE_DIR = DEV_DATA_DIR / 'output' / 'dna-methylation'

# Unphased (combined) methylation BEDs from aligned_bam_to_cpg_scores
METH_COUNT_DIR = METH_BASE_DIR / 'CEPH1463.GRCh38.hifi.count.pedmec-phased' # output dir of aligned_bam_to_cpg_scores (containing count-based unphased meth)
METH_MODEL_DIR = METH_BASE_DIR / 'CEPH1463.GRCh38.hifi.model.pedmec-phased' # output dir of aligned_bam_to_cpg_scores (containing model-based unphased meth)

def combined_meth_paths(uid):
    """Return (count_combined, model_combined) paths for a sample."""
    return (
        str(METH_COUNT_DIR / f'{uid}.GRCh38.haplotagged.combined.bed.gz'), # unphased count-based meth from aligned_bam_to_cpg_scores
        str(METH_MODEL_DIR / f'{uid}.GRCh38.haplotagged.combined.bed.gz'), # unphased model-based meth from aligned_bam_to_cpg_scores
    )

KID_METH_COUNT_COMBINED, KID_METH_MODEL_COMBINED = combined_meth_paths(KID_ID)
DAD_METH_COUNT_COMBINED, DAD_METH_MODEL_COMBINED = combined_meth_paths(DAD_ID)
MOM_METH_COUNT_COMBINED, MOM_METH_MODEL_COMBINED = combined_meth_paths(MOM_ID)

# Parent-phased methylation BED
PARENT_PHASED_DIR = METH_BASE_DIR / 'CEPH1463.GRCh38.hifi.parent-phased' # output dir of phase_meth_to_parent_haps.py
BED_METH_PARENT_PHASED = str(PARENT_PHASED_DIR / 'trio.dna-methylation.bed') # parent-phased methylation levels from phase_meth_to_parent_haps.py

# Heterozygous sites at which bit-vectors are mismatched, from phase_meth_to_parent_haps.py
BED_HET_SITE_MISMATCHES_PAT = str(PARENT_PHASED_DIR / f'{KID_ID}.bit-vector-sites-mismatches.paternal.bed')
BED_HET_SITE_MISMATCHES_MAT = str(PARENT_PHASED_DIR / f'{KID_ID}.bit-vector-sites-mismatches.maternal.bed')

# All CpG sites in the reference genome
OUTPUT_DIR = METH_BASE_DIR / 'CEPH1463.GRCh38.hifi.parent-phased.all-cpgs'
BED_ALL_CPGS_IN_REFERENCE = str(OUTPUT_DIR / 'all_cpg_sites_in_reference.bed') # output of write_all_cpgs_in_reference.py

# Joint-called VCF
VCF_JOINT_CALLED = str(DEV_DATA_DIR / 'input' / 'CEPH-1463.joint.GRCh38.deepvariant.glnexus.vcf.gz')

## Get all CpG sites in reference genome

In [3]:
import util
importlib.reload(util)
from util import read_all_cpgs_in_reference

DF_ALL_CPGS_IN_REFERENCE = read_all_cpgs_in_reference(BED_ALL_CPGS_IN_REFERENCE)
DF_ALL_CPGS_IN_REFERENCE

shape: (2_375_159, 3)
┌───────┬───────────┬───────────┐
│ chrom ┆ start     ┆ end       │
│ ---   ┆ ---       ┆ ---       │
│ str   ┆ i64       ┆ i64       │
╞═══════╪═══════════╪═══════════╡
│ chr1  ┆ 10468     ┆ 10469     │
│ chr1  ┆ 10470     ┆ 10471     │
│ chr1  ┆ 10483     ┆ 10484     │
│ chr1  ┆ 10488     ┆ 10489     │
│ chr1  ┆ 10492     ┆ 10493     │
│ chr1  ┆ 10496     ┆ 10497     │
│ chr1  ┆ 10524     ┆ 10525     │
│ chr1  ┆ 10541     ┆ 10542     │
│ chr1  ┆ 10562     ┆ 10563     │
│ chr1  ┆ 10570     ┆ 10571     │
│ chr1  ┆ 10576     ┆ 10577     │
│ chr1  ┆ 10578     ┆ 10579     │
│ chr1  ┆ 10588     ┆ 10589     │
│ …     ┆ …         ┆ …         │
│ chr1  ┆ 248945480 ┆ 248945481 │
│ chr1  ┆ 248945566 ┆ 248945567 │
│ chr1  ┆ 248945578 ┆ 248945579 │
│ chr1  ┆ 248945590 ┆ 248945591 │
│ chr1  ┆ 248945596 ┆ 248945597 │
│ chr1  ┆ 248945602 ┆ 248945603 │
│ chr1  ┆ 248945608 ┆ 248945609 │
│ chr1  ┆ 248945649 ┆ 248945650 │
│ chr1  ┆ 248945656 ┆ 248945657 │
│ chr1  ┆ 248945669 ┆ 248945670 │
│ chr1  ┆ 248945672 ┆ 248945673 │
│ chr1  ┆ 248945687 ┆ 248945688 │
└───────┴───────────┴───────────┘

## Read in unphased DNA methylation at CpG sites for kid, dad, and mom

In [4]:
import expand_to_all_cpgs_trio 
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import read_meth_unphased_trio

DF_METH_UNPHASED = read_meth_unphased_trio(
    bed_meth_count_kid=KID_METH_COUNT_COMBINED,
    bed_meth_model_kid=KID_METH_MODEL_COMBINED,
    bed_meth_count_dad=DAD_METH_COUNT_COMBINED,
    bed_meth_model_dad=DAD_METH_MODEL_COMBINED,
    bed_meth_count_mom=MOM_METH_COUNT_COMBINED,
    bed_meth_model_mom=MOM_METH_MODEL_COMBINED,
)
DF_METH_UNPHASED

shape: (38_327, 12)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_ ┆ … ┆ methylation ┆ total_read ┆ methylatio ┆ methylatio │
│ ---   ┆ ---     ┆ ---     ┆ count_kid   ┆   ┆ _level_dad_ ┆ _count_mom ┆ n_level_mo ┆ n_level_mo │
│ str   ┆ i64     ┆ i64     ┆ ---         ┆   ┆ model       ┆ ---        ┆ m_count    ┆ m_model    │
│       ┆         ┆         ┆ i64         ┆   ┆ ---         ┆ i64        ┆ ---        ┆ ---        │
│       ┆         ┆         ┆             ┆   ┆ f64         ┆            ┆ f64        ┆ f64        │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 986903  ┆ 986904  ┆ 10          ┆ … ┆ 0.49        ┆ 21         ┆ 0.476      ┆ 0.538      │
│ chr1  ┆ 986966  ┆ 986967  ┆ 10          ┆ … ┆ 0.897       ┆ 21         ┆ 0.524      ┆ 0.772      │
│ chr1  ┆ 987029  ┆ 987030  ┆ 10          ┆ … ┆ 0.817       ┆ 21         ┆ 0.476      ┆ 0.523      │
│ chr1  ┆ 987116  ┆ 987117  ┆ 10          ┆ … ┆ 0.536       ┆ 21         ┆ 0.667      ┆ 0.842      │
│ chr1  ┆ 987154  ┆ 987155  ┆ 11          ┆ … ┆ 0.864       ┆ 21         ┆ 0.619      ┆ 0.9        │
│ chr1  ┆ 987343  ┆ 987344  ┆ 11          ┆ … ┆ 0.888       ┆ 22         ┆ 0.591      ┆ 0.923      │
│ chr1  ┆ 987366  ┆ 987367  ┆ 11          ┆ … ┆ 0.526       ┆ 22         ┆ 0.818      ┆ 0.946      │
│ chr1  ┆ 987425  ┆ 987426  ┆ 12          ┆ … ┆ 0.923       ┆ 21         ┆ 0.905      ┆ 0.962      │
│ chr1  ┆ 987427  ┆ 987428  ┆ 12          ┆ … ┆ 0.935       ┆ 22         ┆ 0.864      ┆ 0.933      │
│ chr1  ┆ 987437  ┆ 987438  ┆ 12          ┆ … ┆ 0.772       ┆ 22         ┆ 0.364      ┆ 0.543      │
│ chr1  ┆ 987473  ┆ 987474  ┆ 12          ┆ … ┆ 0.702       ┆ 22         ┆ 0.409      ┆ 0.398      │
│ chr1  ┆ 987504  ┆ 987505  ┆ 12          ┆ … ┆ 0.32        ┆ 23         ┆ 0.652      ┆ 0.694      │
│ chr1  ┆ 987536  ┆ 987537  ┆ 12          ┆ … ┆ 0.874       ┆ 23         ┆ 0.478      ┆ 0.494      │
│ …     ┆ …       ┆ …       ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ chr1  ┆ 1144904 ┆ 1144905 ┆ null        ┆ … ┆ null        ┆ 23         ┆ 0.217      ┆ 0.344      │
│ chr1  ┆ 983987  ┆ 983988  ┆ null        ┆ … ┆ null        ┆ 12         ┆ 0.583      ┆ 0.685      │
│ chr1  ┆ 1131447 ┆ 1131448 ┆ null        ┆ … ┆ null        ┆ 33         ┆ 0.364      ┆ 0.454      │
│ chr1  ┆ 985689  ┆ 985690  ┆ null        ┆ … ┆ null        ┆ 18         ┆ 0.222      ┆ 0.082      │
│ chr1  ┆ 1026828 ┆ 1026829 ┆ null        ┆ … ┆ null        ┆ 36         ┆ 0.111      ┆ 0.059      │
│ chr1  ┆ 986340  ┆ 986341  ┆ null        ┆ … ┆ null        ┆ 19         ┆ 0.737      ┆ 0.793      │
│ chr1  ┆ 984900  ┆ 984901  ┆ null        ┆ … ┆ null        ┆ 14         ┆ 0.786      ┆ 0.874      │
│ chr1  ┆ 982261  ┆ 982262  ┆ null        ┆ … ┆ null        ┆ 10         ┆ 0.4        ┆ 0.284      │
│ chr1  ┆ 983258  ┆ 983259  ┆ null        ┆ … ┆ null        ┆ 12         ┆ 0.5        ┆ 0.627      │
│ chr1  ┆ 983109  ┆ 983110  ┆ null        ┆ … ┆ null        ┆ 12         ┆ 0.75       ┆ 0.855      │
│ chr1  ┆ 983499  ┆ 983500  ┆ null        ┆ … ┆ null        ┆ 12         ┆ 0.75       ┆ 0.794      │
│ chr1  ┆ 982813  ┆ 982814  ┆ null        ┆ … ┆ null        ┆ 12         ┆ 1.0        ┆ 0.95       │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

## Read in parent-phased DNA methylation at CpG sites

In [5]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import read_meth_parent_phased

DF_METH_PARENT_PHASED = read_meth_parent_phased(BED_METH_PARENT_PHASED)
DF_METH_PARENT_PHASED

shape: (37_471, 31)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_ ┆ … ┆ end_hap_map ┆ maternal_h ┆ maternal_c ┆ num_het_SN │
│ ---   ┆ ---     ┆ ---     ┆ count_kid_p ┆   ┆ _block_mat  ┆ aplotype   ┆ oncordance ┆ Vs_in_mom  │
│ str   ┆ i64     ┆ i64     ┆ at          ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│       ┆         ┆         ┆ ---         ┆   ┆ i64         ┆ str        ┆ f64        ┆ i64        │
│       ┆         ┆         ┆ i64         ┆   ┆             ┆            ┆            ┆            │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 990862  ┆ 990863  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 990869  ┆ 990870  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 990914  ┆ 990915  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 990924  ┆ 990925  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 990948  ┆ 990949  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 990956  ┆ 990957  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991280  ┆ 991281  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991431  ┆ 991432  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991460  ┆ 991461  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991584  ┆ 991585  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991587  ┆ 991588  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991589  ┆ 991590  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991744  ┆ 991745  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ …     ┆ …       ┆ …       ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ chr1  ┆ 1248443 ┆ 1248444 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1133466 ┆ 1133467 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1246076 ┆ 1246077 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1931383 ┆ 1931384 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1931510 ┆ 1931511 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 985572  ┆ 985573  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 1023571 ┆ 1023572 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1249212 ┆ 1249213 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 987819  ┆ 987820  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 986547  ┆ 986548  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 1245993 ┆ 1245994 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1931608 ┆ 1931609 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

## Expand the dataframe of parent-phased methylation levels to include all CpG sites in reference and sample genome, and unphased methylation levels (where available)

In [6]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import expand_meth_to_all_cpgs

DF_METH_PARENT_PHASED_ALL_CPGS = expand_meth_to_all_cpgs(DF_ALL_CPGS_IN_REFERENCE, DF_METH_UNPHASED, DF_METH_PARENT_PHASED)
DF_METH_PARENT_PHASED_ALL_CPGS

shape: (2_375_696, 40)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_ ┆ … ┆ end_hap_map ┆ maternal_h ┆ maternal_c ┆ num_het_SN │
│ ---   ┆ ---     ┆ ---     ┆ count_kid   ┆   ┆ _block_mat  ┆ aplotype   ┆ oncordance ┆ Vs_in_mom  │
│ str   ┆ i64     ┆ i64     ┆ ---         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│       ┆         ┆         ┆ i64         ┆   ┆ i64         ┆ str        ┆ f64        ┆ i64        │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 10468   ┆ 10469   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10470   ┆ 10471   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10483   ┆ 10484   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10488   ┆ 10489   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10492   ┆ 10493   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10496   ┆ 10497   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10524   ┆ 10525   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10541   ┆ 10542   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10562   ┆ 10563   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10570   ┆ 10571   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10576   ┆ 10577   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10578   ┆ 10579   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10588   ┆ 10589   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ …     ┆ …       ┆ …       ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ chr1  ┆ 1078260 ┆ 1078261 ┆ 12          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1948119 ┆ 1948120 ┆ 56          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1982122 ┆ 1982123 ┆ 45          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1585587 ┆ 1585588 ┆ 41          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1344632 ┆ 1344633 ┆ 35          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1928249 ┆ 1928250 ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 1351516 ┆ 1351517 ┆ 30          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1934374 ┆ 1934375 ┆ 23          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 996408  ┆ 996409  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 1912982 ┆ 1912983 ┆ 45          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1708361 ┆ 1708362 ┆ 49          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1664299 ┆ 1664300 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

## Add proximity of each CpG site to heterozygous sites at which bit-vectors are mismatched

In [7]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import compute_proximity_to_mismatched_heterozygous_sites

DF_METH_PARENT_PHASED_ALL_CPGS = compute_proximity_to_mismatched_heterozygous_sites(
    DF_METH_PARENT_PHASED_ALL_CPGS,
    BED_HET_SITE_MISMATCHES_PAT,
    BED_HET_SITE_MISMATCHES_MAT,
)
DF_METH_PARENT_PHASED_ALL_CPGS

shape: (2_375_696, 42)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_ ┆ … ┆ maternal_co ┆ num_het_SN ┆ is_within_ ┆ is_within_ │
│ ---   ┆ ---     ┆ ---     ┆ count_kid   ┆   ┆ ncordance   ┆ Vs_in_mom  ┆ 50bp_of_mi ┆ 50bp_of_mi │
│ str   ┆ i64     ┆ i64     ┆ ---         ┆   ┆ ---         ┆ ---        ┆ smatch_sit ┆ smatch_sit │
│       ┆         ┆         ┆ i64         ┆   ┆ f64         ┆ i64        ┆ …          ┆ …          │
│       ┆         ┆         ┆             ┆   ┆             ┆            ┆ ---        ┆ ---        │
│       ┆         ┆         ┆             ┆   ┆             ┆            ┆ bool       ┆ bool       │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 10468   ┆ 10469   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10470   ┆ 10471   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10483   ┆ 10484   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10488   ┆ 10489   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10492   ┆ 10493   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10496   ┆ 10497   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10524   ┆ 10525   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10541   ┆ 10542   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10562   ┆ 10563   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10570   ┆ 10571   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10576   ┆ 10577   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10578   ┆ 10579   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10588   ┆ 10589   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ …     ┆ …       ┆ …       ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ chr1  ┆ 1078260 ┆ 1078261 ┆ 12          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1948119 ┆ 1948120 ┆ 56          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1982122 ┆ 1982123 ┆ 45          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1585587 ┆ 1585588 ┆ 41          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1344632 ┆ 1344633 ┆ 35          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1928249 ┆ 1928250 ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 1351516 ┆ 1351517 ┆ 30          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1934374 ┆ 1934375 ┆ 23          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 996408  ┆ 996409  ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 1912982 ┆ 1912983 ┆ 45          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1708361 ┆ 1708362 ┆ 49          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1664299 ┆ 1664300 ┆ null        ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

## Bed file enables downstream computation of methylation change upon transmission between generations

https://github.com/quinlan-lab/tapestry/blob/main/images/tapestry.trio.alignments.png

https://github.com/quinlan-lab/tapestry/blob/main/images/tapestry.trio.methylation.png

In [8]:
version_sort(DF_METH_PARENT_PHASED_ALL_CPGS.select([
    "chrom", "start", "end",
    "methylation_level_kid_pat_count", "methylation_level_dad_A_count", "methylation_level_dad_B_count",
    "paternal_haplotype", "paternal_concordance", "is_within_50bp_of_mismatch_site_pat"
]).filter(
    (pl.col('start') > 1989000) & 
    (pl.col('end') < 1989300)
))

shape: (8, 9)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ methylation ┆ … ┆ methylation ┆ paternal_h ┆ paternal_c ┆ is_within_ │
│ ---   ┆ ---     ┆ ---     ┆ _level_kid_ ┆   ┆ _level_dad_ ┆ aplotype   ┆ oncordance ┆ 50bp_of_mi │
│ str   ┆ i64     ┆ i64     ┆ pat_coun…   ┆   ┆ B_count     ┆ ---        ┆ ---        ┆ smatch_sit │
│       ┆         ┆         ┆ ---         ┆   ┆ ---         ┆ str        ┆ f64        ┆ …          │
│       ┆         ┆         ┆ f64         ┆   ┆ f64         ┆            ┆            ┆ ---        │
│       ┆         ┆         ┆             ┆   ┆             ┆            ┆            ┆ bool       │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1989147 ┆ 1989148 ┆ 0.964       ┆ … ┆ 0.679       ┆ B          ┆ 0.999055   ┆ false      │
│ chr1  ┆ 1989153 ┆ 1989154 ┆ 0.75        ┆ … ┆ 0.714       ┆ B          ┆ 0.999055   ┆ false      │
│ chr1  ┆ 1989187 ┆ 1989188 ┆ 0.821       ┆ … ┆ 0.929       ┆ B          ┆ 0.999055   ┆ false      │
│ chr1  ┆ 1989199 ┆ 1989200 ┆ 0.714       ┆ … ┆ 0.714       ┆ B          ┆ 0.999055   ┆ false      │
│ chr1  ┆ 1989206 ┆ 1989207 ┆ 0.714       ┆ … ┆ 0.714       ┆ B          ┆ 0.999055   ┆ false      │
│ chr1  ┆ 1989227 ┆ 1989228 ┆ 0.679       ┆ … ┆ 0.571       ┆ B          ┆ 0.999055   ┆ false      │
│ chr1  ┆ 1989285 ┆ 1989286 ┆ 0.964       ┆ … ┆ 0.929       ┆ B          ┆ 0.999055   ┆ false      │
│ chr1  ┆ 1989291 ┆ 1989292 ┆ 0.964       ┆ … ┆ 0.929       ┆ B          ┆ 0.999055   ┆ false      │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

![chr1_1989000_1989300](images/chr1_1989000_1989300.png)

## QC Statistics

In [9]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import compute_fraction_of_cpgs_that_are_close_to_mismatches

compute_fraction_of_cpgs_that_are_close_to_mismatches(DF_METH_PARENT_PHASED_ALL_CPGS)

Percentage of CpG sites (in reference and sample genome, and on phasable chroms) that are within 50bp of a paternal heterozygous mismatch site: 0.000%
Percentage of CpG sites (in reference and sample genome, and on phasable chroms) that are within 50bp of a maternal heterozygous mismatch site: 0.038%

In [10]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import compute_methylation_coverage_qc

compute_methylation_coverage_qc(DF_METH_PARENT_PHASED_ALL_CPGS)

Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which count-based methylation is phased to kid_pat haplotype: 1.41%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which count-based methylation is phased to kid_mat haplotype: 1.38%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which count-based methylation is phased to at least one parental haplotype (kid): 1.45%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which count-based methylation is phased to both parental haplotypes (kid): 1.33%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which count-based unphased methylation is reported for kid: 1.59%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which model-based methylation is phased to kid_pat haplotype: 1.41%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which model-based methylation is phased to kid_mat haplotype: 1.38%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which model-based methylation is phased to at least one parental haplotype (kid): 1.45%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which model-based methylation is phased to both parental haplotypes (kid): 1.33%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which model-based unphased methylation is reported for kid: 1.59%

## Overlap CpGs with joint-called SNVs

In [11]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import get_joint_called_variants

pl.Config.set_tbl_rows(30)

DF_JOINT_CALLED_VARIANTS = get_joint_called_variants(KID_ID, DAD_ID, MOM_ID, VCF_JOINT_CALLED)
DF_JOINT_CALLED_VARIANTS

shape: (3_755, 9)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ allele_1_ki ┆ … ┆ allele_1_da ┆ allele_2_d ┆ allele_1_m ┆ allele_2_m │
│ ---   ┆ ---     ┆ ---     ┆ d           ┆   ┆ d           ┆ ad         ┆ om         ┆ om         │
│ str   ┆ i64     ┆ i64     ┆ ---         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│       ┆         ┆         ┆ str         ┆   ┆ str         ┆ str        ┆ str        ┆ str        │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1000078 ┆ 1000079 ┆ 1           ┆ … ┆ 1           ┆ 1          ┆ 1          ┆ 1          │
│ chr1  ┆ 1000111 ┆ 1000112 ┆ 1           ┆ … ┆ 1           ┆ 1          ┆ 1          ┆ 1          │
│ chr1  ┆ 1000290 ┆ 1000291 ┆ 0           ┆ … ┆ 0           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1000334 ┆ 1000335 ┆ 1           ┆ … ┆ 1           ┆ 0          ┆ 1          ┆ 0          │
│ chr1  ┆ 1000452 ┆ 1000453 ┆ 1           ┆ … ┆ 1           ┆ 1          ┆ 1          ┆ 1          │
│ chr1  ┆ 1000551 ┆ 1000552 ┆ 0           ┆ … ┆ 0           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1000730 ┆ 1000731 ┆ 0           ┆ … ┆ 0           ┆ 1          ┆ 0          ┆ 1          │
│ chr1  ┆ 1000813 ┆ 1000814 ┆ 1           ┆ … ┆ 1           ┆ 1          ┆ 1          ┆ 1          │
│ chr1  ┆ 1000829 ┆ 1000830 ┆ 1           ┆ … ┆ 1           ┆ 1          ┆ 1          ┆ 1          │
│ chr1  ┆ 1001332 ┆ 1001333 ┆ 0           ┆ … ┆ 0           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1001869 ┆ 1001870 ┆ 0           ┆ … ┆ 0           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1002307 ┆ 1002308 ┆ 1           ┆ … ┆ 1           ┆ 1          ┆ 1          ┆ 1          │
│ chr1  ┆ 1002416 ┆ 1002417 ┆ 0           ┆ … ┆ 0           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1002735 ┆ 1002736 ┆ 1           ┆ … ┆ 1           ┆ 1          ┆ 1          ┆ 1          │
│ chr1  ┆ 1002744 ┆ 1002745 ┆ 1           ┆ … ┆ 1           ┆ 0          ┆ 1          ┆ 0          │
│ …     ┆ …       ┆ …       ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ chr1  ┆ 1998048 ┆ 1998049 ┆ 0           ┆ … ┆ 0           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1998226 ┆ 1998227 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1998394 ┆ 1998395 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1998419 ┆ 1998420 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1998437 ┆ 1998438 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1998654 ┆ 1998655 ┆ 0           ┆ … ┆ 1           ┆ 1          ┆ 0          ┆ 0          │
│ chr1  ┆ 1998951 ┆ 1998952 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1999072 ┆ 1999073 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1999113 ┆ 1999114 ┆ 0           ┆ … ┆ 0           ┆ 1          ┆ 0          ┆ 0          │
│ chr1  ┆ 1999314 ┆ 1999315 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1999365 ┆ 1999366 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1999503 ┆ 1999504 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1999541 ┆ 1999542 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1999755 ┆ 1999756 ┆ 0           ┆ … ┆ 1           ┆ 0          ┆ 0          ┆ 0          │
│ chr1  ┆ 1999859 ┆ 1999860 ┆ 0           ┆ … ┆ 0           ┆ 1          ┆ 0          ┆ 0          │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [12]:
# An example of CpG site creation 
# A site that is CpG in only one haplotype of the sample, and not CpG in the reference sequence
# chr1:1173872 A>G creates a CpG on one haplotype, with a methylation level of 0.0 reported on the other haplotype

![chr1-1,173,852-1,173,891](images/chr1-1,173,852-1,173,891.png)

In [13]:
pl.Config.set_tbl_rows(10)

# variant at this CpG site: 
# note that the IGV screenshot (above) reports the pedmed-phased variant, but the dataframe (below) reports the corrresponding unphased variant
DF_JOINT_CALLED_VARIANTS.filter(
    (pl.col("chrom") == 'chr1') & 
    (pl.col("start") == 1173871)
)

shape: (1, 9)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ allele_1_ki ┆ … ┆ allele_1_da ┆ allele_2_d ┆ allele_1_m ┆ allele_2_m │
│ ---   ┆ ---     ┆ ---     ┆ d           ┆   ┆ d           ┆ ad         ┆ om         ┆ om         │
│ str   ┆ i64     ┆ i64     ┆ ---         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│       ┆         ┆         ┆ str         ┆   ┆ str         ┆ str        ┆ str        ┆ str        │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1173871 ┆ 1173872 ┆ 0           ┆ … ┆ 0           ┆ 1          ┆ 1          ┆ 0          │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [14]:
# Methylation at this CpG site on Dad B is 0.0
# It should be None as there is no CpG on that haplotype
# Similar for Mom C

DF_METH_PARENT_PHASED_ALL_CPGS.filter(
    (pl.col("chrom") == 'chr1') & 
    (pl.col("start") == 1173870)
)

shape: (1, 42)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_ ┆ … ┆ maternal_co ┆ num_het_SN ┆ is_within_ ┆ is_within_ │
│ ---   ┆ ---     ┆ ---     ┆ count_kid   ┆   ┆ ncordance   ┆ Vs_in_mom  ┆ 50bp_of_mi ┆ 50bp_of_mi │
│ str   ┆ i64     ┆ i64     ┆ ---         ┆   ┆ ---         ┆ ---        ┆ smatch_sit ┆ smatch_sit │
│       ┆         ┆         ┆ i64         ┆   ┆ f64         ┆ i64        ┆ …          ┆ …          │
│       ┆         ┆         ┆             ┆   ┆             ┆            ┆ ---        ┆ ---        │
│       ┆         ┆         ┆             ┆   ┆             ┆            ┆ bool       ┆ bool       │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1173870 ┆ 1173871 ┆ null        ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ true       │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [15]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import label_with_variants

DF_METH_PARENT_PHASED_ALL_CPGS_WITH_VARIANT_LABEL = label_with_variants(DF_METH_PARENT_PHASED_ALL_CPGS, DF_JOINT_CALLED_VARIANTS)

In [16]:
DF_METH_PARENT_PHASED_ALL_CPGS_WITH_VARIANT_LABEL.filter(
    (pl.col("chrom") == 'chr1') & 
    (pl.col("start_cpg") == 1173870)
)

shape: (1, 51)
┌───────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start_cpg ┆ end_cpg ┆ total_read ┆ … ┆ allele_2_d ┆ allele_1_m ┆ allele_2_m ┆ num_SNVs_o │
│ ---   ┆ ---       ┆ ---     ┆ _count_kid ┆   ┆ ad         ┆ om         ┆ om         ┆ verlapping │
│ str   ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ _CG        │
│       ┆           ┆         ┆ i64        ┆   ┆ str        ┆ str        ┆ str        ┆ ---        │
│       ┆           ┆         ┆            ┆   ┆            ┆            ┆            ┆ u32        │
╞═══════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1173870   ┆ 1173872 ┆ null       ┆ … ┆ 1          ┆ 1          ┆ 0          ┆ 1          │
└───────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

## Label each unique CpG record with a flag indicating whether it is allele-specific

In [17]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import label_cpgs_as_allele_specific

DF_METH_PARENT_PHASED_ALL_CPGS_WITH_ALLELE_SPECIFIC_FLAG = label_cpgs_as_allele_specific(
    DF_METH_PARENT_PHASED_ALL_CPGS_WITH_VARIANT_LABEL,
) 
DF_METH_PARENT_PHASED_ALL_CPGS_WITH_ALLELE_SPECIFIC_FLAG.filter(
    pl.col('cpg_overlaps_at_least_one_snv')
)

shape: (1_430, 49)
┌───────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start_cpg ┆ end_cpg ┆ total_read ┆ … ┆ snv_genoty ┆ cpg_is_all ┆ snv_genoty ┆ cpg_is_all │
│ ---   ┆ ---       ┆ ---     ┆ _count_kid ┆   ┆ pes_dad    ┆ ele_specif ┆ pes_mom    ┆ ele_specif │
│ str   ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ic_dad     ┆ ---        ┆ ic_mom     │
│       ┆           ┆         ┆ i64        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│       ┆           ┆         ┆            ┆   ┆            ┆ bool       ┆            ┆ bool       │
╞═══════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1000110   ┆ 1000112 ┆ null       ┆ … ┆ hom        ┆ false      ┆ hom        ┆ false      │
│ chr1  ┆ 1000334   ┆ 1000336 ┆ 44         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1000451   ┆ 1000453 ┆ 42         ┆ … ┆ hom        ┆ false      ┆ hom        ┆ false      │
│ chr1  ┆ 1000452   ┆ 1000454 ┆ null       ┆ … ┆ hom        ┆ false      ┆ hom        ┆ false      │
│ chr1  ┆ 1000551   ┆ 1000553 ┆ 44         ┆ … ┆ hom        ┆ false      ┆ hom        ┆ false      │
│ …     ┆ …         ┆ …       ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ chr1  ┆ 1998653   ┆ 1998655 ┆ 54         ┆ … ┆ hom        ┆ false      ┆ hom        ┆ false      │
│ chr1  ┆ 1999113   ┆ 1999115 ┆ null       ┆ … ┆ het        ┆ true       ┆ hom        ┆ false      │
│ chr1  ┆ 1999364   ┆ 1999366 ┆ 54         ┆ … ┆ het        ┆ true       ┆ hom        ┆ false      │
│ chr1  ┆ 1999503   ┆ 1999505 ┆ 53         ┆ … ┆ het        ┆ true       ┆ hom        ┆ false      │
│ chr1  ┆ 1999541   ┆ 1999543 ┆ 53         ┆ … ┆ het        ┆ true       ┆ hom        ┆ false      │
└───────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

### Sanity checking

In [18]:
# CGs that overlap 1 SNV that is het in kid indeed have zero methylation on one haplotype in kid, and can be flagged for exclusion in imprinting scans in the kid: 
DF_METH_PARENT_PHASED_ALL_CPGS_WITH_ALLELE_SPECIFIC_FLAG.filter(pl.col("snv_genotypes_kid") == "het").sample(10, seed=42)

shape: (10, 49)
┌───────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start_cpg ┆ end_cpg ┆ total_read ┆ … ┆ snv_genoty ┆ cpg_is_all ┆ snv_genoty ┆ cpg_is_all │
│ ---   ┆ ---       ┆ ---     ┆ _count_kid ┆   ┆ pes_dad    ┆ ele_specif ┆ pes_mom    ┆ ele_specif │
│ str   ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ic_dad     ┆ ---        ┆ ic_mom     │
│       ┆           ┆         ┆ i64        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│       ┆           ┆         ┆            ┆   ┆            ┆ bool       ┆            ┆ bool       │
╞═══════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1976989   ┆ 1976991 ┆ 46         ┆ … ┆ hom        ┆ false      ┆ hom        ┆ false      │
│ chr1  ┆ 1302447   ┆ 1302449 ┆ 43         ┆ … ┆ hom        ┆ false      ┆ het        ┆ true       │
│ chr1  ┆ 1993897   ┆ 1993899 ┆ 50         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1743467   ┆ 1743469 ┆ 56         ┆ … ┆ het        ┆ true       ┆ hom        ┆ false      │
│ chr1  ┆ 1976572   ┆ 1976574 ┆ 46         ┆ … ┆ hom        ┆ false      ┆ hom        ┆ false      │
│ chr1  ┆ 1687151   ┆ 1687153 ┆ 41         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1053550   ┆ 1053552 ┆ 34         ┆ … ┆ het        ┆ true       ┆ hom        ┆ false      │
│ chr1  ┆ 1688585   ┆ 1688587 ┆ 43         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1077570   ┆ 1077572 ┆ null       ┆ … ┆ .          ┆ false      ┆ hom        ┆ false      │
│ chr1  ┆ 1987154   ┆ 1987156 ┆ 53         ┆ … ┆ hom        ┆ false      ┆ hom        ┆ false      │
└───────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [19]:
# CGs that overlap 1 SNV that is het in dad indeed have zero methylation on one haplotype in dad, and can be flagged for exclusion in imprinting scans in dad: 
DF_METH_PARENT_PHASED_ALL_CPGS_WITH_ALLELE_SPECIFIC_FLAG.filter(pl.col("snv_genotypes_dad") == "het").sample(10, seed=42)

shape: (10, 49)
┌───────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start_cpg ┆ end_cpg ┆ total_read ┆ … ┆ snv_genoty ┆ cpg_is_all ┆ snv_genoty ┆ cpg_is_all │
│ ---   ┆ ---       ┆ ---     ┆ _count_kid ┆   ┆ pes_dad    ┆ ele_specif ┆ pes_mom    ┆ ele_specif │
│ str   ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ic_dad     ┆ ---        ┆ ic_mom     │
│       ┆           ┆         ┆ i64        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│       ┆           ┆         ┆            ┆   ┆            ┆ bool       ┆            ┆ bool       │
╞═══════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1792925   ┆ 1792927 ┆ 80         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1453960   ┆ 1453962 ┆ 40         ┆ … ┆ het        ┆ true       ┆ hom        ┆ false      │
│ chr1  ┆ 1981542   ┆ 1981544 ┆ 45         ┆ … ┆ het        ┆ true       ┆ hom        ┆ false      │
│ chr1  ┆ 1734262   ┆ 1734264 ┆ null       ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1773847   ┆ 1773849 ┆ null       ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1671993   ┆ 1671995 ┆ 53         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1072050   ┆ 1072052 ┆ 24         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1684265   ┆ 1684267 ┆ 38         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1163333   ┆ 1163335 ┆ null       ┆ … ┆ het        ┆ true       ┆ hom        ┆ false      │
│ chr1  ┆ 1945120   ┆ 1945122 ┆ null       ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
└───────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [20]:
# CGs that overlap 1 SNV that is het in mom indeed have zero methylation on one haplotype in mom, and can be flagged for exclusion in imprinting scans in mom: 
DF_METH_PARENT_PHASED_ALL_CPGS_WITH_ALLELE_SPECIFIC_FLAG.filter(pl.col("snv_genotypes_mom") == "het").sample(10, seed=42)

shape: (10, 49)
┌───────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start_cpg ┆ end_cpg ┆ total_read ┆ … ┆ snv_genoty ┆ cpg_is_all ┆ snv_genoty ┆ cpg_is_all │
│ ---   ┆ ---       ┆ ---     ┆ _count_kid ┆   ┆ pes_dad    ┆ ele_specif ┆ pes_mom    ┆ ele_specif │
│ str   ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ic_dad     ┆ ---        ┆ ic_mom     │
│       ┆           ┆         ┆ i64        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│       ┆           ┆         ┆            ┆   ┆            ┆ bool       ┆            ┆ bool       │
╞═══════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1837454   ┆ 1837456 ┆ null       ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1437954   ┆ 1437956 ┆ 26         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1950070   ┆ 1950072 ┆ null       ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1742468   ┆ 1742470 ┆ null       ┆ … ┆ hom        ┆ false      ┆ het        ┆ true       │
│ chr1  ┆ 1795440   ┆ 1795442 ┆ 67         ┆ … ┆ hom        ┆ false      ┆ het        ┆ true       │
│ chr1  ┆ 1699126   ┆ 1699128 ┆ 53         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1065262   ┆ 1065264 ┆ 23         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1705854   ┆ 1705856 ┆ 48         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1127257   ┆ 1127259 ┆ 51         ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
│ chr1  ┆ 1942085   ┆ 1942087 ┆ null       ┆ … ┆ het        ┆ true       ┆ het        ┆ true       │
└───────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [21]:
# CGs that overlap 2 SNVs, the first of which is het in kid, indeed have zero methylation on one haplotype in kid, or have null methylation levels because of a deletion, and can be flagged for exclusion in imprinting scans in kid: 
DF_METH_PARENT_PHASED_ALL_CPGS_WITH_ALLELE_SPECIFIC_FLAG.filter(pl.col("snv_genotypes_kid").str.contains("het,"))

shape: (5, 49)
┌───────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start_cpg ┆ end_cpg ┆ total_read ┆ … ┆ snv_genoty ┆ cpg_is_all ┆ snv_genoty ┆ cpg_is_all │
│ ---   ┆ ---       ┆ ---     ┆ _count_kid ┆   ┆ pes_dad    ┆ ele_specif ┆ pes_mom    ┆ ele_specif │
│ str   ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ic_dad     ┆ ---        ┆ ic_mom     │
│       ┆           ┆         ┆ i64        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│       ┆           ┆         ┆            ┆   ┆            ┆ bool       ┆            ┆ bool       │
╞═══════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1076849   ┆ 1076851 ┆ 11         ┆ … ┆ .,.        ┆ false      ┆ hom,hom    ┆ false      │
│ chr1  ┆ 1077239   ┆ 1077241 ┆ 10         ┆ … ┆ .,.        ┆ false      ┆ hom,hom    ┆ false      │
│ chr1  ┆ 1077808   ┆ 1077810 ┆ 19         ┆ … ┆ .,.        ┆ false      ┆ het,hom    ┆ true       │
│ chr1  ┆ 1079339   ┆ 1079341 ┆ 27         ┆ … ┆ het,het    ┆ true       ┆ het,het    ┆ true       │
│ chr1  ┆ 1606010   ┆ 1606012 ┆ null       ┆ … ┆ .,hom      ┆ false      ┆ het,hom    ┆ true       │
└───────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [22]:
# CGs that overlap 2 SNVs, the second of which is het in kid, indeed have zero methylation on one haplotype in kid, or have null methylation levels because of a deletion, and can be flagged for exclusion in imprinting scans in kid: 
DF_METH_PARENT_PHASED_ALL_CPGS_WITH_ALLELE_SPECIFIC_FLAG.filter(pl.col("snv_genotypes_kid").str.contains(",het"))

shape: (2, 49)
┌───────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start_cpg ┆ end_cpg ┆ total_read ┆ … ┆ snv_genoty ┆ cpg_is_all ┆ snv_genoty ┆ cpg_is_all │
│ ---   ┆ ---       ┆ ---     ┆ _count_kid ┆   ┆ pes_dad    ┆ ele_specif ┆ pes_mom    ┆ ele_specif │
│ str   ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ic_dad     ┆ ---        ┆ ic_mom     │
│       ┆           ┆         ┆ i64        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│       ┆           ┆         ┆            ┆   ┆            ┆ bool       ┆            ┆ bool       │
╞═══════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1079339   ┆ 1079341 ┆ 27         ┆ … ┆ het,het    ┆ true       ┆ het,het    ┆ true       │
│ chr1  ┆ 1606010   ┆ 1606012 ┆ null       ┆ … ┆ .,hom      ┆ false      ┆ het,hom    ┆ true       │
└───────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [23]:
# CGs that overlap 2 SNVs, the first of which is het in dad, indeed have zero methylation on one haplotype in dad, or have null methylation levels because of a deletion, and can be flagged for exclusion in imprinting scans in dad: 
DF_METH_PARENT_PHASED_ALL_CPGS_WITH_ALLELE_SPECIFIC_FLAG.filter(pl.col("snv_genotypes_dad").str.contains("het,"))

shape: (3, 49)
┌───────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start_cpg ┆ end_cpg ┆ total_read ┆ … ┆ snv_genoty ┆ cpg_is_all ┆ snv_genoty ┆ cpg_is_all │
│ ---   ┆ ---       ┆ ---     ┆ _count_kid ┆   ┆ pes_dad    ┆ ele_specif ┆ pes_mom    ┆ ele_specif │
│ str   ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ic_dad     ┆ ---        ┆ ic_mom     │
│       ┆           ┆         ┆ i64        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│       ┆           ┆         ┆            ┆   ┆            ┆ bool       ┆            ┆ bool       │
╞═══════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1079339   ┆ 1079341 ┆ 27         ┆ … ┆ het,het    ┆ true       ┆ het,het    ┆ true       │
│ chr1  ┆ 1497604   ┆ 1497606 ┆ null       ┆ … ┆ het,het    ┆ true       ┆ hom,hom    ┆ false      │
│ chr1  ┆ 1534217   ┆ 1534219 ┆ 57         ┆ … ┆ het,het    ┆ true       ┆ hom,hom    ┆ false      │
└───────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [24]:
# CGs that overlap 2 SNVs, the second of which is het in dad, indeed have zero methylation on one haplotype in dad, or have null methylation levels because of a deletion, and can be flagged for exclusion in imprinting scans in dad: 
DF_METH_PARENT_PHASED_ALL_CPGS_WITH_ALLELE_SPECIFIC_FLAG.filter(pl.col("snv_genotypes_dad").str.contains(",het"))

shape: (5, 49)
┌───────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start_cpg ┆ end_cpg ┆ total_read ┆ … ┆ snv_genoty ┆ cpg_is_all ┆ snv_genoty ┆ cpg_is_all │
│ ---   ┆ ---       ┆ ---     ┆ _count_kid ┆   ┆ pes_dad    ┆ ele_specif ┆ pes_mom    ┆ ele_specif │
│ str   ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ic_dad     ┆ ---        ┆ ic_mom     │
│       ┆           ┆         ┆ i64        ┆   ┆ str        ┆ ---        ┆ str        ┆ ---        │
│       ┆           ┆         ┆            ┆   ┆            ┆ bool       ┆            ┆ bool       │
╞═══════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1079339   ┆ 1079341 ┆ 27         ┆ … ┆ het,het    ┆ true       ┆ het,het    ┆ true       │
│ chr1  ┆ 1497604   ┆ 1497606 ┆ null       ┆ … ┆ het,het    ┆ true       ┆ hom,hom    ┆ false      │
│ chr1  ┆ 1534217   ┆ 1534219 ┆ 57         ┆ … ┆ het,het    ┆ true       ┆ hom,hom    ┆ false      │
│ chr1  ┆ 1605667   ┆ 1605669 ┆ 48         ┆ … ┆ .,het      ┆ true       ┆ het,het    ┆ true       │
│ chr1  ┆ 1924206   ┆ 1924208 ┆ null       ┆ … ┆ hom,het    ┆ true       ┆ hom,het    ┆ true       │
└───────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘