## Setup

In [1]:
import importlib
from pathlib import Path
import sys
import polars as pl

pl.Config.set_tbl_rows(25)

REPO_DIR = Path('.').resolve().parent
DEV_DATA_DIR = REPO_DIR / 'trio_dev_data'

sys.path.insert(0, str(REPO_DIR / 'src'))
sys.path.insert(0, str(REPO_DIR / 'src' / 'util'))

In [2]:
KID_ID = 'NA12878'
DAD_ID = 'NA12891'
MOM_ID = 'NA12892'

METH_BASE_DIR = DEV_DATA_DIR / 'output' / 'dna-methylation'

# Unphased (combined) methylation BEDs from aligned_bam_to_cpg_scores
METH_COUNT_DIR = METH_BASE_DIR / 'CEPH1463.GRCh38.hifi.count.pedmec-phased' # output dir of aligned_bam_to_cpg_scores (containing count-based unphased meth)
METH_MODEL_DIR = METH_BASE_DIR / 'CEPH1463.GRCh38.hifi.model.pedmec-phased' # output dir of aligned_bam_to_cpg_scores (containing model-based unphased meth)

def combined_meth_paths(uid):
    """Return (count_combined, model_combined) paths for a sample."""
    return (
        str(METH_COUNT_DIR / f'{uid}.GRCh38.haplotagged.combined.bed.gz'), # unphased count-based meth from aligned_bam_to_cpg_scores
        str(METH_MODEL_DIR / f'{uid}.GRCh38.haplotagged.combined.bed.gz'), # unphased model-based meth from aligned_bam_to_cpg_scores
    )

KID_METH_COUNT_COMBINED, KID_METH_MODEL_COMBINED = combined_meth_paths(KID_ID)
DAD_METH_COUNT_COMBINED, DAD_METH_MODEL_COMBINED = combined_meth_paths(DAD_ID)
MOM_METH_COUNT_COMBINED, MOM_METH_MODEL_COMBINED = combined_meth_paths(MOM_ID)

# Parent-phased methylation BED
PARENT_PHASED_DIR = METH_BASE_DIR / 'CEPH1463.GRCh38.hifi.parent-phased' # output dir of phase_meth_to_parent_haps.py
BED_METH_PARENT_PHASED = str(PARENT_PHASED_DIR / 'trio.dna-methylation.bed') # parent-phased methylation levels from phase_meth_to_parent_haps.py

# Heterozygous sites at which bit-vectors are mismatched, from phase_meth_to_parent_haps.py
BED_HET_SITE_MISMATCHES_PAT = str(PARENT_PHASED_DIR / f'{KID_ID}.bit-vector-sites-mismatches.paternal.bed')
BED_HET_SITE_MISMATCHES_MAT = str(PARENT_PHASED_DIR / f'{KID_ID}.bit-vector-sites-mismatches.maternal.bed')

# All CpG sites in the reference genome
OUTPUT_DIR = METH_BASE_DIR / 'CEPH1463.GRCh38.hifi.parent-phased.all-cpgs'
BED_ALL_CPGS_IN_REFERENCE = str(OUTPUT_DIR / 'all_cpg_sites_in_reference.bed') # output of write_all_cpgs_in_reference.py

## Get all CpG sites in reference genome

In [3]:
import util
importlib.reload(util)
from util import read_all_cpgs_in_reference

DF_ALL_CPGS_IN_REFERENCE = read_all_cpgs_in_reference(BED_ALL_CPGS_IN_REFERENCE)
DF_ALL_CPGS_IN_REFERENCE

shape: (2_375_159, 3)
┌───────┬───────────┬───────────┐
│ chrom ┆ start     ┆ end       │
│ ---   ┆ ---       ┆ ---       │
│ str   ┆ i64       ┆ i64       │
╞═══════╪═══════════╪═══════════╡
│ chr1  ┆ 10468     ┆ 10469     │
│ chr1  ┆ 10470     ┆ 10471     │
│ chr1  ┆ 10483     ┆ 10484     │
│ chr1  ┆ 10488     ┆ 10489     │
│ chr1  ┆ 10492     ┆ 10493     │
│ chr1  ┆ 10496     ┆ 10497     │
│ chr1  ┆ 10524     ┆ 10525     │
│ chr1  ┆ 10541     ┆ 10542     │
│ chr1  ┆ 10562     ┆ 10563     │
│ chr1  ┆ 10570     ┆ 10571     │
│ chr1  ┆ 10576     ┆ 10577     │
│ chr1  ┆ 10578     ┆ 10579     │
│ chr1  ┆ 10588     ┆ 10589     │
│ …     ┆ …         ┆ …         │
│ chr1  ┆ 248945480 ┆ 248945481 │
│ chr1  ┆ 248945566 ┆ 248945567 │
│ chr1  ┆ 248945578 ┆ 248945579 │
│ chr1  ┆ 248945590 ┆ 248945591 │
│ chr1  ┆ 248945596 ┆ 248945597 │
│ chr1  ┆ 248945602 ┆ 248945603 │
│ chr1  ┆ 248945608 ┆ 248945609 │
│ chr1  ┆ 248945649 ┆ 248945650 │
│ chr1  ┆ 248945656 ┆ 248945657 │
│ chr1  ┆ 248945669 ┆ 248945670 │
│ chr1  ┆ 248945672 ┆ 248945673 │
│ chr1  ┆ 248945687 ┆ 248945688 │
└───────┴───────────┴───────────┘

## Read in unphased DNA methylation at CpG sites for kid, dad, and mom

In [4]:
import expand_to_all_cpgs_trio 
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import read_meth_unphased_trio

DF_METH_UNPHASED = read_meth_unphased_trio(
    bed_meth_count_kid=KID_METH_COUNT_COMBINED,
    bed_meth_model_kid=KID_METH_MODEL_COMBINED,
    bed_meth_count_dad=DAD_METH_COUNT_COMBINED,
    bed_meth_model_dad=DAD_METH_MODEL_COMBINED,
    bed_meth_count_mom=MOM_METH_COUNT_COMBINED,
    bed_meth_model_mom=MOM_METH_MODEL_COMBINED,
)
DF_METH_UNPHASED

shape: (38_327, 12)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_ ┆ … ┆ methylation ┆ total_read ┆ methylatio ┆ methylatio │
│ ---   ┆ ---     ┆ ---     ┆ count_kid   ┆   ┆ _level_dad_ ┆ _count_mom ┆ n_level_mo ┆ n_level_mo │
│ str   ┆ i64     ┆ i64     ┆ ---         ┆   ┆ model       ┆ ---        ┆ m_count    ┆ m_model    │
│       ┆         ┆         ┆ i64         ┆   ┆ ---         ┆ i64        ┆ ---        ┆ ---        │
│       ┆         ┆         ┆             ┆   ┆ f64         ┆            ┆ f64        ┆ f64        │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 986903  ┆ 986904  ┆ 10          ┆ … ┆ 0.49        ┆ 21         ┆ 0.476      ┆ 0.538      │
│ chr1  ┆ 986966  ┆ 986967  ┆ 10          ┆ … ┆ 0.897       ┆ 21         ┆ 0.524      ┆ 0.772      │
│ chr1  ┆ 987029  ┆ 987030  ┆ 10          ┆ … ┆ 0.817       ┆ 21         ┆ 0.476      ┆ 0.523      │
│ chr1  ┆ 987116  ┆ 987117  ┆ 10          ┆ … ┆ 0.536       ┆ 21         ┆ 0.667      ┆ 0.842      │
│ chr1  ┆ 987154  ┆ 987155  ┆ 11          ┆ … ┆ 0.864       ┆ 21         ┆ 0.619      ┆ 0.9        │
│ chr1  ┆ 987343  ┆ 987344  ┆ 11          ┆ … ┆ 0.888       ┆ 22         ┆ 0.591      ┆ 0.923      │
│ chr1  ┆ 987366  ┆ 987367  ┆ 11          ┆ … ┆ 0.526       ┆ 22         ┆ 0.818      ┆ 0.946      │
│ chr1  ┆ 987425  ┆ 987426  ┆ 12          ┆ … ┆ 0.923       ┆ 21         ┆ 0.905      ┆ 0.962      │
│ chr1  ┆ 987427  ┆ 987428  ┆ 12          ┆ … ┆ 0.935       ┆ 22         ┆ 0.864      ┆ 0.933      │
│ chr1  ┆ 987437  ┆ 987438  ┆ 12          ┆ … ┆ 0.772       ┆ 22         ┆ 0.364      ┆ 0.543      │
│ chr1  ┆ 987473  ┆ 987474  ┆ 12          ┆ … ┆ 0.702       ┆ 22         ┆ 0.409      ┆ 0.398      │
│ chr1  ┆ 987504  ┆ 987505  ┆ 12          ┆ … ┆ 0.32        ┆ 23         ┆ 0.652      ┆ 0.694      │
│ chr1  ┆ 987536  ┆ 987537  ┆ 12          ┆ … ┆ 0.874       ┆ 23         ┆ 0.478      ┆ 0.494      │
│ …     ┆ …       ┆ …       ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ chr1  ┆ 1131447 ┆ 1131448 ┆ null        ┆ … ┆ null        ┆ 33         ┆ 0.364      ┆ 0.454      │
│ chr1  ┆ 1132481 ┆ 1132482 ┆ null        ┆ … ┆ null        ┆ 31         ┆ 0.29       ┆ 0.451      │
│ chr1  ┆ 1140234 ┆ 1140235 ┆ null        ┆ … ┆ null        ┆ 14         ┆ 0.857      ┆ 0.933      │
│ chr1  ┆ 1029861 ┆ 1029862 ┆ null        ┆ … ┆ null        ┆ 36         ┆ 0.361      ┆ 0.7        │
│ chr1  ┆ 985125  ┆ 985126  ┆ null        ┆ … ┆ null        ┆ 15         ┆ 0.533      ┆ 0.597      │
│ chr1  ┆ 983235  ┆ 983236  ┆ null        ┆ … ┆ null        ┆ 12         ┆ 0.833      ┆ 0.926      │
│ chr1  ┆ 985267  ┆ 985268  ┆ null        ┆ … ┆ null        ┆ 16         ┆ 0.938      ┆ 0.917      │
│ chr1  ┆ 983109  ┆ 983110  ┆ null        ┆ … ┆ null        ┆ 12         ┆ 0.75       ┆ 0.855      │
│ chr1  ┆ 986189  ┆ 986190  ┆ null        ┆ … ┆ null        ┆ 19         ┆ 0.895      ┆ 0.949      │
│ chr1  ┆ 983252  ┆ 983253  ┆ null        ┆ … ┆ null        ┆ 12         ┆ 0.5        ┆ 0.577      │
│ chr1  ┆ 985395  ┆ 985396  ┆ null        ┆ … ┆ null        ┆ 16         ┆ 0.563      ┆ 0.556      │
│ chr1  ┆ 983082  ┆ 983083  ┆ null        ┆ … ┆ null        ┆ 12         ┆ 0.583      ┆ 0.584      │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

## Read in parent-phased DNA methylation at CpG sites

In [5]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import read_meth_parent_phased

DF_METH_PARENT_PHASED = read_meth_parent_phased(BED_METH_PARENT_PHASED)
DF_METH_PARENT_PHASED

shape: (37_471, 31)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_ ┆ … ┆ end_hap_map ┆ maternal_h ┆ maternal_c ┆ num_het_SN │
│ ---   ┆ ---     ┆ ---     ┆ count_kid_p ┆   ┆ _block_mat  ┆ aplotype   ┆ oncordance ┆ Vs_in_mom  │
│ str   ┆ i64     ┆ i64     ┆ at          ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│       ┆         ┆         ┆ ---         ┆   ┆ i64         ┆ str        ┆ f64        ┆ i64        │
│       ┆         ┆         ┆ i64         ┆   ┆             ┆            ┆            ┆            │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 990862  ┆ 990863  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 990869  ┆ 990870  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 990914  ┆ 990915  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 990924  ┆ 990925  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 990948  ┆ 990949  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 990956  ┆ 990957  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991280  ┆ 991281  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991431  ┆ 991432  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991460  ┆ 991461  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991584  ┆ 991585  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991587  ┆ 991588  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991589  ┆ 991590  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 991744  ┆ 991745  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ …     ┆ …       ┆ …       ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ chr1  ┆ 986547  ┆ 986548  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 1141683 ┆ 1141684 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 986213  ┆ 986214  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 986380  ┆ 986381  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 1592889 ┆ 1592890 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1023523 ┆ 1023524 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1157307 ┆ 1157308 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1248995 ┆ 1248996 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1249139 ┆ 1249140 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1249403 ┆ 1249404 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1248443 ┆ 1248444 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 986384  ┆ 986385  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

## Expand the dataframe of parent-phased methylation levels to include all CpG sites in reference and sample genome, and unphased methylation levels (where available)

In [6]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import expand_meth_to_all_cpgs

DF_METH_PARENT_PHASED_ALL_CPGS = expand_meth_to_all_cpgs(DF_ALL_CPGS_IN_REFERENCE, DF_METH_UNPHASED, DF_METH_PARENT_PHASED)
DF_METH_PARENT_PHASED_ALL_CPGS

shape: (2_375_696, 40)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_ ┆ … ┆ end_hap_map ┆ maternal_h ┆ maternal_c ┆ num_het_SN │
│ ---   ┆ ---     ┆ ---     ┆ count_kid   ┆   ┆ _block_mat  ┆ aplotype   ┆ oncordance ┆ Vs_in_mom  │
│ str   ┆ i64     ┆ i64     ┆ ---         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│       ┆         ┆         ┆ i64         ┆   ┆ i64         ┆ str        ┆ f64        ┆ i64        │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 10468   ┆ 10469   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10470   ┆ 10471   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10483   ┆ 10484   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10488   ┆ 10489   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10492   ┆ 10493   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10496   ┆ 10497   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10524   ┆ 10525   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10541   ┆ 10542   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10562   ┆ 10563   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10570   ┆ 10571   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10576   ┆ 10577   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10578   ┆ 10579   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 10588   ┆ 10589   ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ …     ┆ …       ┆ …       ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ chr1  ┆ 996491  ┆ 996492  ┆ null        ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 1979856 ┆ 1979857 ┆ 25          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1013488 ┆ 1013489 ┆ 40          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1078290 ┆ 1078291 ┆ 12          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1942085 ┆ 1942086 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 995784  ┆ 995785  ┆ 35          ┆ … ┆ null        ┆ null       ┆ null       ┆ null       │
│ chr1  ┆ 1078019 ┆ 1078020 ┆ 18          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1968991 ┆ 1968992 ┆ 29          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1586423 ┆ 1586424 ┆ 41          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1030164 ┆ 1030165 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1455923 ┆ 1455924 ┆ null        ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
│ chr1  ┆ 1349459 ┆ 1349460 ┆ 34          ┆ … ┆ 1993898     ┆ D          ┆ 0.721598   ┆ 801        │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

## Add proximity of each CpG site to heterozygous sites at which bit-vectors are mismatched

In [7]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import compute_proximity_to_mismatched_heterozygous_sites

DF_METH_PARENT_PHASED_ALL_CPGS = compute_proximity_to_mismatched_heterozygous_sites(
    DF_METH_PARENT_PHASED_ALL_CPGS,
    BED_HET_SITE_MISMATCHES_PAT,
    BED_HET_SITE_MISMATCHES_MAT,
)
DF_METH_PARENT_PHASED_ALL_CPGS

shape: (2_375_696, 42)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_ ┆ … ┆ maternal_co ┆ num_het_SN ┆ is_within_ ┆ is_within_ │
│ ---   ┆ ---     ┆ ---     ┆ count_kid   ┆   ┆ ncordance   ┆ Vs_in_mom  ┆ 50bp_of_mi ┆ 50bp_of_mi │
│ str   ┆ i64     ┆ i64     ┆ ---         ┆   ┆ ---         ┆ ---        ┆ smatch_sit ┆ smatch_sit │
│       ┆         ┆         ┆ i64         ┆   ┆ f64         ┆ i64        ┆ …          ┆ …          │
│       ┆         ┆         ┆             ┆   ┆             ┆            ┆ ---        ┆ ---        │
│       ┆         ┆         ┆             ┆   ┆             ┆            ┆ bool       ┆ bool       │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 10468   ┆ 10469   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10470   ┆ 10471   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10483   ┆ 10484   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10488   ┆ 10489   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10492   ┆ 10493   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10496   ┆ 10497   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10524   ┆ 10525   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10541   ┆ 10542   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10562   ┆ 10563   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10570   ┆ 10571   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10576   ┆ 10577   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10578   ┆ 10579   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 10588   ┆ 10589   ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ …     ┆ …       ┆ …       ┆ …           ┆ … ┆ …           ┆ …          ┆ …          ┆ …          │
│ chr1  ┆ 996491  ┆ 996492  ┆ null        ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 1979856 ┆ 1979857 ┆ 25          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1013488 ┆ 1013489 ┆ 40          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1078290 ┆ 1078291 ┆ 12          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1942085 ┆ 1942086 ┆ null        ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 995784  ┆ 995785  ┆ 35          ┆ … ┆ null        ┆ null       ┆ false      ┆ false      │
│ chr1  ┆ 1078019 ┆ 1078020 ┆ 18          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1968991 ┆ 1968992 ┆ 29          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1586423 ┆ 1586424 ┆ 41          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1030164 ┆ 1030165 ┆ null        ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ true       │
│ chr1  ┆ 1455923 ┆ 1455924 ┆ null        ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
│ chr1  ┆ 1349459 ┆ 1349460 ┆ 34          ┆ … ┆ 0.721598    ┆ 801        ┆ false      ┆ false      │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

## QC Statistics

In [8]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import compute_fraction_of_cpgs_that_are_close_to_mismatches

compute_fraction_of_cpgs_that_are_close_to_mismatches(DF_METH_PARENT_PHASED_ALL_CPGS)

Percentage of CpG sites (in reference and sample genome, and on phasable chroms) that are within 50bp of a paternal heterozygous mismatch site: 0.000%
Percentage of CpG sites (in reference and sample genome, and on phasable chroms) that are within 50bp of a maternal heterozygous mismatch site: 0.038%

In [9]:
importlib.reload(expand_to_all_cpgs_trio)
from expand_to_all_cpgs_trio import compute_methylation_coverage_qc

compute_methylation_coverage_qc(DF_METH_PARENT_PHASED_ALL_CPGS)

Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which count-based methylation is phased to kid_pat haplotype: 1.41%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which count-based methylation is phased to kid_mat haplotype: 1.38%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which count-based methylation is phased to at least one parental haplotype (kid): 1.45%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which count-based methylation is phased to both parental haplotypes (kid): 1.33%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which count-based unphased methylation is reported for kid: 1.59%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which model-based methylation is phased to kid_pat haplotype: 1.41%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which model-based methylation is phased to kid_mat haplotype: 1.38%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which model-based methylation is phased to at least one parental haplotype (kid): 1.45%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which model-based methylation is phased to both parental haplotypes (kid): 1.33%
Percentage of CpG sites (in reference and sample genomes, and on phasable chroms) at which model-based unphased methylation is reported for kid: 1.59%