### Setup

In [1]:
import importlib
import polars as pl

pl.Config.set_tbl_rows(25)

from pathlib import Path

REPO_DIR = Path('.').resolve().parent
DEV_DATA_DIR = REPO_DIR / 'trio-dev-data'

import sys
sys.path.insert(0, str(REPO_DIR / 'src'))
sys.path.insert(0, str(REPO_DIR / 'src' / 'util'))

In [2]:
KID_ID = 'NA12878'
DAD_ID = 'NA12891'
MOM_ID = 'NA12892'

VCF_TRIO_PHASED = str(DEV_DATA_DIR / 'output' / 'trio-phasing' / 'CEPH-1463.joint.GRCh38.deepvariant.glnexus.phased.vcf.gz')

def blocks_tsv_path(uid):
    return str(DEV_DATA_DIR / 'output' / 'trio-phasing' / f'CEPH-1463.joint.GRCh38.deepvariant.glnexus.phased.{uid}.blocks.tsv')

BLOCKS_TSV_KID = blocks_tsv_path(KID_ID)
BLOCKS_TSV_DAD = blocks_tsv_path(DAD_ID)
BLOCKS_TSV_MOM = blocks_tsv_path(MOM_ID)

In [3]:
METH_BASE_DIR = DEV_DATA_DIR / 'output' / 'dna-methylation'

def meth_bed_paths(uid):
    """Return (count_hap1, count_hap2, model_hap1, model_hap2) paths for a sample."""
    count_dir = METH_BASE_DIR / 'CEPH1463.GRCh38.hifi.count.pedmec-phased'
    model_dir = METH_BASE_DIR / 'CEPH1463.GRCh38.hifi.model.pedmec-phased'
    return (
        str(count_dir / f'{uid}.GRCh38.haplotagged.hap1.bed.gz'),
        str(count_dir / f'{uid}.GRCh38.haplotagged.hap2.bed.gz'),
        str(model_dir / f'{uid}.GRCh38.haplotagged.hap1.bed.gz'),
        str(model_dir / f'{uid}.GRCh38.haplotagged.hap2.bed.gz'),
    )

KID_METH = meth_bed_paths(KID_ID)
DAD_METH = meth_bed_paths(DAD_ID)
MOM_METH = meth_bed_paths(MOM_ID)

### Get phase blocks for each individual (pre-computed by `run-whatshap.sh`)

In [4]:
import phasing_trio
importlib.reload(phasing_trio)
from phasing_trio import get_phase_blocks

DF_BLOCKS_KID = get_phase_blocks(BLOCKS_TSV_KID, KID_ID)
DF_BLOCKS_DAD = get_phase_blocks(BLOCKS_TSV_DAD, DAD_ID)
DF_BLOCKS_MOM = get_phase_blocks(BLOCKS_TSV_MOM, MOM_ID)

print(f'Kid phase blocks: {len(DF_BLOCKS_KID)}')
print(f'Dad phase blocks: {len(DF_BLOCKS_DAD)}')
print(f'Mom phase blocks: {len(DF_BLOCKS_MOM)}')

Kid phase blocks: 1
Dad phase blocks: 1
Mom phase blocks: 1

In [5]:
DF_BLOCKS_KID

shape: (1, 5)
┌───────┬─────────┬─────────┬────────────────┬──────────────┐
│ chrom ┆ start   ┆ end     ┆ phase_block_id ┆ num_variants │
│ ---   ┆ ---     ┆ ---     ┆ ---            ┆ ---          │
│ str   ┆ i64     ┆ i64     ┆ str            ┆ i64          │
╞═══════╪═════════╪═════════╪════════════════╪══════════════╡
│ chr1  ┆ 1000334 ┆ 1999756 ┆ 1000335        ┆ 802          │
└───────┴─────────┴─────────┴────────────────┴──────────────┘

In [6]:
DF_BLOCKS_DAD

shape: (1, 5)
┌───────┬─────────┬─────────┬────────────────┬──────────────┐
│ chrom ┆ start   ┆ end     ┆ phase_block_id ┆ num_variants │
│ ---   ┆ ---     ┆ ---     ┆ ---            ┆ ---          │
│ str   ┆ i64     ┆ i64     ┆ str            ┆ i64          │
╞═══════╪═════════╪═════════╪════════════════╪══════════════╡
│ chr1  ┆ 1000334 ┆ 1999860 ┆ 1000335        ┆ 1231         │
└───────┴─────────┴─────────┴────────────────┴──────────────┘

In [7]:
DF_BLOCKS_MOM

shape: (1, 5)
┌───────┬─────────┬─────────┬────────────────┬──────────────┐
│ chrom ┆ start   ┆ end     ┆ phase_block_id ┆ num_variants │
│ ---   ┆ ---     ┆ ---     ┆ ---            ┆ ---          │
│ str   ┆ i64     ┆ i64     ┆ str            ┆ i64          │
╞═══════╪═════════╪═════════╪════════════════╪══════════════╡
│ chr1  ┆ 1000334 ┆ 1993898 ┆ 1000335        ┆ 949          │
└───────┴─────────┴─────────┴────────────────┴──────────────┘

### Get paired parent-child alleles from the WhatsHap trio-phased VCF (PedMEC algorithm)

In [8]:
import phasing_trio
importlib.reload(phasing_trio)
from phasing_trio import get_all_phasing

DF_KID_DAD, DF_KID_MOM = get_all_phasing(
    VCF_TRIO_PHASED, KID_ID, DAD_ID, MOM_ID,
    DF_BLOCKS_KID, DF_BLOCKS_DAD, DF_BLOCKS_MOM,
)

print(f'Dad-het sites: {len(DF_KID_DAD)}')
print(f'Mom-het sites: {len(DF_KID_MOM)}')

Dad-het sites: 1058
Mom-het sites: 801

In [9]:
DF_KID_DAD

shape: (1_058, 12)
┌───────┬─────────┬─────────┬─────┬───┬───────────────┬──────────────┬──────────────┬──────────────┐
│ chrom ┆ start   ┆ end     ┆ REF ┆ … ┆ start_phase_b ┆ end_phase_bl ┆ start_phase_ ┆ end_phase_bl │
│ ---   ┆ ---     ┆ ---     ┆ --- ┆   ┆ lock_kid      ┆ ock_kid      ┆ block_dad    ┆ ock_dad      │
│ str   ┆ i64     ┆ i64     ┆ str ┆   ┆ ---           ┆ ---          ┆ ---          ┆ ---          │
│       ┆         ┆         ┆     ┆   ┆ i64           ┆ i64          ┆ i64          ┆ i64          │
╞═══════╪═════════╪═════════╪═════╪═══╪═══════════════╪══════════════╪══════════════╪══════════════╡
│ chr1  ┆ 1000334 ┆ 1000335 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1000730 ┆ 1000731 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1002744 ┆ 1002745 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1004624 ┆ 1004625 ┆ A   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1004715 ┆ 1004716 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1004822 ┆ 1004823 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1005903 ┆ 1005904 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1005953 ┆ 1005954 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1006158 ┆ 1006159 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1008306 ┆ 1008307 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1008587 ┆ 1008588 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1009183 ┆ 1009184 ┆ T   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1014227 ┆ 1014228 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ …     ┆ …       ┆ …       ┆ …   ┆ … ┆ …             ┆ …            ┆ …            ┆ …            │
│ chr1  ┆ 1998226 ┆ 1998227 ┆ A   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1998394 ┆ 1998395 ┆ A   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1998419 ┆ 1998420 ┆ T   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1998437 ┆ 1998438 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1998951 ┆ 1998952 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1999072 ┆ 1999073 ┆ A   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1999113 ┆ 1999114 ┆ T   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1999314 ┆ 1999315 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1999365 ┆ 1999366 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1999503 ┆ 1999504 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1999541 ┆ 1999542 ┆ T   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
│ chr1  ┆ 1999755 ┆ 1999756 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1999860      │
└───────┴─────────┴─────────┴─────┴───┴───────────────┴──────────────┴──────────────┴──────────────┘

In [10]:
DF_KID_MOM

shape: (801, 12)
┌───────┬─────────┬─────────┬─────┬───┬───────────────┬──────────────┬──────────────┬──────────────┐
│ chrom ┆ start   ┆ end     ┆ REF ┆ … ┆ start_phase_b ┆ end_phase_bl ┆ start_phase_ ┆ end_phase_bl │
│ ---   ┆ ---     ┆ ---     ┆ --- ┆   ┆ lock_kid      ┆ ock_kid      ┆ block_mom    ┆ ock_mom      │
│ str   ┆ i64     ┆ i64     ┆ str ┆   ┆ ---           ┆ ---          ┆ ---          ┆ ---          │
│       ┆         ┆         ┆     ┆   ┆ i64           ┆ i64          ┆ i64          ┆ i64          │
╞═══════╪═════════╪═════════╪═════╪═══╪═══════════════╪══════════════╪══════════════╪══════════════╡
│ chr1  ┆ 1000334 ┆ 1000335 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1000730 ┆ 1000731 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1002744 ┆ 1002745 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1004624 ┆ 1004625 ┆ A   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1004715 ┆ 1004716 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1005903 ┆ 1005904 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1005953 ┆ 1005954 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1006158 ┆ 1006159 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1008306 ┆ 1008307 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1008587 ┆ 1008588 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1009183 ┆ 1009184 ┆ T   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1014227 ┆ 1014228 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1014862 ┆ 1014863 ┆ A   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ …     ┆ …       ┆ …       ┆ …   ┆ … ┆ …             ┆ …            ┆ …            ┆ …            │
│ chr1  ┆ 1957635 ┆ 1957636 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1958060 ┆ 1958061 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1959823 ┆ 1959824 ┆ A   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1962221 ┆ 1962222 ┆ T   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1970505 ┆ 1970506 ┆ T   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1991394 ┆ 1991395 ┆ T   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1991777 ┆ 1991778 ┆ A   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1991821 ┆ 1991822 ┆ G   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1991840 ┆ 1991841 ┆ T   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1991866 ┆ 1991867 ┆ A   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1993853 ┆ 1993854 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
│ chr1  ┆ 1993897 ┆ 1993898 ┆ C   ┆ … ┆ 1000334       ┆ 1999756      ┆ 1000334      ┆ 1993898      │
└───────┴─────────┴─────────┴─────┴───┴───────────────┴──────────────┴──────────────┴──────────────┘

### Construct a Hap Map, consisting of intervals ("hap-map blocks") in which haplotypes in the kid are mapped to haplotypes in the parents

Labeling convention:
- **A** = dad's hap1, **B** = dad's hap2 (fixed)
- **C** = mom's hap1, **D** = mom's hap2 (fixed)
- Kid's hap1 (paternal) matches A or B per block; kid's hap2 (maternal) matches C or D per block

Note that A, B, C, D are only defined within hap-map blocks, not chromosome-wide, as is the case for the pedigree-wise workflow

In [11]:
import hap_map_trio
importlib.reload(hap_map_trio)
from hap_map_trio import get_hap_map

DF_HAP_MAP_PAT, DF_HAP_MAP_MAT, DF_MISMATCH_PAT, DF_MISMATCH_MAT = get_hap_map(DF_KID_DAD, DF_KID_MOM)

In [12]:
DF_HAP_MAP_PAT

shape: (1, 6)
┌───────┬─────────┬─────────┬────────────────────┬───────────────────────┬────────────────────────┐
│ chrom ┆ start   ┆ end     ┆ paternal_haplotype ┆ haplotype_concordance ┆ num_het_SNVs_in_parent │
│ ---   ┆ ---     ┆ ---     ┆ ---                ┆ ---                   ┆ ---                    │
│ str   ┆ i64     ┆ i64     ┆ str                ┆ f64                   ┆ i64                    │
╞═══════╪═════════╪═════════╪════════════════════╪═══════════════════════╪════════════════════════╡
│ chr1  ┆ 1000334 ┆ 1999756 ┆ A                  ┆ 0.999055              ┆ 1058                   │
└───────┴─────────┴─────────┴────────────────────┴───────────────────────┴────────────────────────┘

In [13]:
DF_MISMATCH_PAT

shape: (1, 5)
┌───────┬─────────┬─────────┬─────┬─────┐
│ chrom ┆ start   ┆ end     ┆ REF ┆ ALT │
│ ---   ┆ ---     ┆ ---     ┆ --- ┆ --- │
│ str   ┆ i64     ┆ i64     ┆ str ┆ str │
╞═══════╪═════════╪═════════╪═════╪═════╡
│ chr1  ┆ 1076638 ┆ 1076639 ┆ G   ┆ A   │
└───────┴─────────┴─────────┴─────┴─────┘

In [14]:
DF_HAP_MAP_MAT

shape: (1, 6)
┌───────┬─────────┬─────────┬────────────────────┬───────────────────────┬────────────────────────┐
│ chrom ┆ start   ┆ end     ┆ maternal_haplotype ┆ haplotype_concordance ┆ num_het_SNVs_in_parent │
│ ---   ┆ ---     ┆ ---     ┆ ---                ┆ ---                   ┆ ---                    │
│ str   ┆ i64     ┆ i64     ┆ str                ┆ f64                   ┆ i64                    │
╞═══════╪═════════╪═════════╪════════════════════╪═══════════════════════╪════════════════════════╡
│ chr1  ┆ 1000334 ┆ 1993898 ┆ C                  ┆ 0.982522              ┆ 801                    │
└───────┴─────────┴─────────┴────────────────────┴───────────────────────┴────────────────────────┘

In [15]:
DF_MISMATCH_MAT

shape: (14, 5)
┌───────┬─────────┬─────────┬─────┬─────┐
│ chrom ┆ start   ┆ end     ┆ REF ┆ ALT │
│ ---   ┆ ---     ┆ ---     ┆ --- ┆ --- │
│ str   ┆ i64     ┆ i64     ┆ str ┆ str │
╞═══════╪═════════╪═════════╪═════╪═════╡
│ chr1  ┆ 1289587 ┆ 1289588 ┆ T   ┆ C   │
│ chr1  ┆ 1289720 ┆ 1289721 ┆ T   ┆ C   │
│ chr1  ┆ 1289740 ┆ 1289741 ┆ T   ┆ C   │
│ chr1  ┆ 1289903 ┆ 1289904 ┆ T   ┆ C   │
│ chr1  ┆ 1302448 ┆ 1302449 ┆ G   ┆ A   │
│ chr1  ┆ 1308548 ┆ 1308549 ┆ G   ┆ T   │
│ chr1  ┆ 1317019 ┆ 1317020 ┆ C   ┆ T   │
│ chr1  ┆ 1324156 ┆ 1324157 ┆ G   ┆ A   │
│ chr1  ┆ 1324165 ┆ 1324166 ┆ G   ┆ A   │
│ chr1  ┆ 1324170 ┆ 1324171 ┆ A   ┆ G   │
│ chr1  ┆ 1340696 ┆ 1340697 ┆ G   ┆ A   │
│ chr1  ┆ 1351200 ┆ 1351201 ┆ G   ┆ C   │
│ chr1  ┆ 1362102 ┆ 1362103 ┆ G   ┆ A   │
│ chr1  ┆ 1382657 ┆ 1382658 ┆ T   ┆ C   │
└───────┴─────────┴─────────┴─────┴─────┘

### Get HiFi DNA methylation levels (both count-based and model-based) in kid, dad, and mom at CpG sites phased to hap1/hap2

In [16]:
import get_meth_hap1_hap2
importlib.reload(get_meth_hap1_hap2)
from get_meth_hap1_hap2 import read_meth_hap1_hap2

DF_METH_COUNT_HAP1_HAP2_KID = read_meth_hap1_hap2(
    pb_cpg_tool_mode='count',
    bed_hap1=KID_METH[0],
    bed_hap2=KID_METH[1],
)
DF_METH_COUNT_HAP1_HAP2_KID

shape: (35_280, 7)
┌───────┬─────────┬─────────┬─────────────────┬─────────────────┬─────────────────┬────────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_coun ┆ methylation_lev ┆ total_read_coun ┆ methylation_le │
│ ---   ┆ ---     ┆ ---     ┆ t_hap1          ┆ el_hap1         ┆ t_hap2          ┆ vel_hap2       │
│ str   ┆ i64     ┆ i64     ┆ ---             ┆ ---             ┆ ---             ┆ ---            │
│       ┆         ┆         ┆ i64             ┆ f64             ┆ i64             ┆ f64            │
╞═══════╪═════════╪═════════╪═════════════════╪═════════════════╪═════════════════╪════════════════╡
│ chr1  ┆ 990862  ┆ 990863  ┆ 10              ┆ 0.7             ┆ null            ┆ null           │
│ chr1  ┆ 990869  ┆ 990870  ┆ 10              ┆ 0.7             ┆ null            ┆ null           │
│ chr1  ┆ 990914  ┆ 990915  ┆ 10              ┆ 0.7             ┆ null            ┆ null           │
│ chr1  ┆ 990924  ┆ 990925  ┆ 10              ┆ 0.7             ┆ null            ┆ null           │
│ chr1  ┆ 990948  ┆ 990949  ┆ 11              ┆ 0.818           ┆ null            ┆ null           │
│ chr1  ┆ 990956  ┆ 990957  ┆ 11              ┆ 0.818           ┆ null            ┆ null           │
│ chr1  ┆ 991280  ┆ 991281  ┆ 11              ┆ 0.818           ┆ null            ┆ null           │
│ chr1  ┆ 991431  ┆ 991432  ┆ 12              ┆ 0.75            ┆ null            ┆ null           │
│ chr1  ┆ 991460  ┆ 991461  ┆ 12              ┆ 0.75            ┆ null            ┆ null           │
│ chr1  ┆ 991584  ┆ 991585  ┆ 12              ┆ 0.917           ┆ null            ┆ null           │
│ chr1  ┆ 991587  ┆ 991588  ┆ 12              ┆ 1.0             ┆ null            ┆ null           │
│ chr1  ┆ 991589  ┆ 991590  ┆ 12              ┆ 0.917           ┆ null            ┆ null           │
│ chr1  ┆ 991744  ┆ 991745  ┆ 12              ┆ 0.75            ┆ null            ┆ null           │
│ …     ┆ …       ┆ …       ┆ …               ┆ …               ┆ …               ┆ …              │
│ chr1  ┆ 2011409 ┆ 2011410 ┆ null            ┆ null            ┆ 12              ┆ 0.75           │
│ chr1  ┆ 2011457 ┆ 2011458 ┆ null            ┆ null            ┆ 12              ┆ 0.833          │
│ chr1  ┆ 2011488 ┆ 2011489 ┆ null            ┆ null            ┆ 11              ┆ 0.545          │
│ chr1  ┆ 2011515 ┆ 2011516 ┆ null            ┆ null            ┆ 11              ┆ 0.909          │
│ chr1  ┆ 2011560 ┆ 2011561 ┆ null            ┆ null            ┆ 11              ┆ 0.818          │
│ chr1  ┆ 2011647 ┆ 2011648 ┆ null            ┆ null            ┆ 10              ┆ 0.7            │
│ chr1  ┆ 2011739 ┆ 2011740 ┆ null            ┆ null            ┆ 10              ┆ 0.6            │
│ chr1  ┆ 2011758 ┆ 2011759 ┆ null            ┆ null            ┆ 10              ┆ 0.8            │
│ chr1  ┆ 2011765 ┆ 2011766 ┆ null            ┆ null            ┆ 10              ┆ 0.7            │
│ chr1  ┆ 2011794 ┆ 2011795 ┆ null            ┆ null            ┆ 10              ┆ 0.6            │
│ chr1  ┆ 2011853 ┆ 2011854 ┆ null            ┆ null            ┆ 10              ┆ 0.7            │
│ chr1  ┆ 2011879 ┆ 2011880 ┆ null            ┆ null            ┆ 10              ┆ 0.7            │
└───────┴─────────┴─────────┴─────────────────┴─────────────────┴─────────────────┴────────────────┘

In [17]:
DF_METH_MODEL_HAP1_HAP2_KID = read_meth_hap1_hap2(
    pb_cpg_tool_mode='model',
    bed_hap1=KID_METH[2],
    bed_hap2=KID_METH[3],
)

In [18]:
DF_METH_COUNT_HAP1_HAP2_DAD = read_meth_hap1_hap2(
    pb_cpg_tool_mode='count',
    bed_hap1=DAD_METH[0],
    bed_hap2=DAD_METH[1],
)

In [19]:
DF_METH_MODEL_HAP1_HAP2_DAD = read_meth_hap1_hap2(
    pb_cpg_tool_mode='model',
    bed_hap1=DAD_METH[2],
    bed_hap2=DAD_METH[3],
)

In [20]:
DF_METH_COUNT_HAP1_HAP2_MOM = read_meth_hap1_hap2(
    pb_cpg_tool_mode='count',
    bed_hap1=MOM_METH[0],
    bed_hap2=MOM_METH[1],
)

In [21]:
DF_METH_MODEL_HAP1_HAP2_MOM = read_meth_hap1_hap2(
    pb_cpg_tool_mode='model',
    bed_hap1=MOM_METH[2],
    bed_hap2=MOM_METH[3],
)

### Phase DNA methylation levels in trio to parent haplotypes

In [22]:
import phase_meth_to_parent_haps
importlib.reload(phase_meth_to_parent_haps)
from phase_meth_to_parent_haps import phase_meth_to_parent_haplotypes

DF_METH_PARENT_PHASED = phase_meth_to_parent_haplotypes(
    DF_METH_COUNT_HAP1_HAP2_KID,
    DF_METH_MODEL_HAP1_HAP2_KID,
    DF_METH_COUNT_HAP1_HAP2_DAD,
    DF_METH_MODEL_HAP1_HAP2_DAD,
    DF_METH_COUNT_HAP1_HAP2_MOM,
    DF_METH_MODEL_HAP1_HAP2_MOM,
    DF_HAP_MAP_PAT,
    DF_HAP_MAP_MAT,
)
DF_METH_PARENT_PHASED.filter(pl.col("start_hap_map_block_pat").is_not_null()).head()

shape: (5, 31)
┌───────┬─────────┬─────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ chrom ┆ start   ┆ end     ┆ total_read_ ┆ … ┆ total_read_ ┆ methylatio ┆ methylatio ┆ methylatio │
│ ---   ┆ ---     ┆ ---     ┆ count_kid_p ┆   ┆ count_mom_D ┆ n_level_mo ┆ n_level_mo ┆ n_level_mo │
│ str   ┆ i64     ┆ i64     ┆ at          ┆   ┆ ---         ┆ m_D_count  ┆ m_C_model  ┆ m_D_model  │
│       ┆         ┆         ┆ ---         ┆   ┆ i64         ┆ ---        ┆ ---        ┆ ---        │
│       ┆         ┆         ┆ i64         ┆   ┆             ┆ f64        ┆ f64        ┆ f64        │
╞═══════╪═════════╪═════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ chr1  ┆ 1000334 ┆ 1000335 ┆ 26          ┆ … ┆ 29          ┆ 0.0        ┆ 0.032      ┆ 0.027      │
│ chr1  ┆ 1000343 ┆ 1000344 ┆ 26          ┆ … ┆ 29          ┆ 0.207      ┆ 0.039      ┆ 0.03       │
│ chr1  ┆ 1000349 ┆ 1000350 ┆ 26          ┆ … ┆ 29          ┆ 0.103      ┆ 0.035      ┆ 0.032      │
│ chr1  ┆ 1000356 ┆ 1000357 ┆ 26          ┆ … ┆ 28          ┆ 0.107      ┆ 0.033      ┆ 0.03       │
│ chr1  ┆ 1000358 ┆ 1000359 ┆ 26          ┆ … ┆ 28          ┆ 0.143      ┆ 0.025      ┆ 0.034      │
└───────┴─────────┴─────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘